apiVersion: v1
kind: Service
metadata:
  name: zip-station-docs-stage
  namespace: zip-station
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: zip-station-docs-stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zip-station-docs-stage
  namespace: zip-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zip-station-docs-stage
  template:
    metadata:
      labels:
        app: zip-station-docs-stage
    spec:
      containers:
      - name: zip-station-docs-stage
        image: "<IMAGE>"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 10
          periodSeconds: 10
      imagePullSecrets:
      - name: ghcr-secret
